export enum EquipmentEnum {
  DUMBBELLS = 'DUMBBELLS',
  'ADJUSTABLE BENCH' = 'ADJUSTABLE_BENCH',
  'POWER LOOPS' = 'POWER_LOOPS',
  'CORE COMFORT MAT' = 'CORE_COMFORT_MAT',
  'YOGA MAT' = 'YOGA_MAT',
  'RESISTANCE LOOPS' = 'RESISTANCE_LOOPS'
}
