export enum OptionsEnum {
  STRENGTH = 'STRENGTH',
  DANCE = 'DANCE',
  'NUTRITION & RECIPES' = 'NUTRITION_RECIPES',
  'MUSCLE BUILDING' = 'MUSCLE_BUILDING',
  HIIT = 'HIIT',
  CARDIO = 'CARDIO',
  CORE = 'CORE',
  'MOBILITY & FLEXIBILITY' = 'MOBILITY_FLEXIBILITY',
  RECOVERY = 'RECOVERY',
  PILATES = 'PILATES',
  YOGA = 'YOGA',
  BOOTCAMP = 'BOOTCAMP',
  'SLIM & SCULPT' = 'SLIM_SCULPT'
}
